### ISSUE TITLE
Add security checker to image

### ISSUE THREAD

**Issue by dpi** [universityofadelaide/s2i-shepherd-drupal#25]
Consider adding https://github.com/fabpot/local-php-security-checker to the image so it can be used reliably as a part of the CI/build process.

**Comment by pingers** [comment]
I'm for it. Happy to do a MR later this week. Cheers!

**Comment by dpi** [comment]
thanks!

**Comment by pingers** [comment]
Fixed in https://github.com/universityofadelaide/s2i-shepherd-drupal/commit/f32328414f0cad2042884bb75acb809008d3cba7
